### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Owned67** [WheteThunger/BetterChinookPath#1]
possible to add a function fro drop randomly on the map or is it already and ive miss understand maybe? ^^

thanks

**Comment by WheteThunger** [comment]
If you want random, just use Chinook Drop Randomizer which I think does that. Note that random dropping has some issues since it can drop in inconvenient places, so the plugin has to ideally account for terrain height, topology, player bases, events, and more.

**Comment by Owned67** [comment]
already using ^^ and saw your plugin about crate modification.

Thanks :)
